### ISSUE TITLE
コンパイル済のファイルをダウンロードできるページがないので、プロジェクトのgithub pagesを作る

### ISSUE THREAD

**Issue by deflis** [ckw-mod/ckw-mod#10]
[ファイルダウンロード機能がなくなったため](https://github.com/blog/1302-goodbye-uploads)、現在コンパイル済のファイルをダウンロードできるページがなくなっている。

そこで、[github pages](http://pages.github.com/)を使うために、ckw-mod.github.comというリポジトリをつくり、そこにWebページをpushしコンパイル済のバイナリをダウンロード出来るようにしたい。

**Comment by southly** [comment]
いつまで残っているか分かりませんが、以前のものはここからダウンロードできます。
- https://github.com/ckw-mod/ckw-mod/downloads

**Comment by southly** [comment]
とりあえず現状あるもので作っておきました。
- http://ckw-mod.github.com/

**Comment by deflis** [comment]
今のページ構成がすごく味気ないので、0.9.1リリースまでにTwitter Bootstrapでも使って綺麗に直しておこうかなと思います。
あと、旧バージョンのダウンロードページも一応用意しておきますね。

**Comment by southly** [comment]
お願いします。

**Comment by deflis** [comment]
ckw-mod/ckw-mod.github.com#2 をクローズしたのでこっちもクローズ
