### ISSUE TITLE
次バージョンリリース作業

### ISSUE THREAD

**Issue by southly** [ckw-mod/ckw-mod#11]
来週あたりに次バージョン (0.9.1) をリリースしたいと思っています。
- ReadMe.txt の更新
- ChangeLog.txt の更新
- Wiki の更新
- version.bat と version.h の更新
- バイナリを用意
- git.sourceforge.jp/gitroot/ckw/ckw.git へプッシュ

必要な作業はこのくらいでしょうか。

入れて欲しいパッチがある人は早めに Pull Requests を送ってください。

**Comment by southly** [comment]
Wiki/マニュアルを更新

**Comment by deflis** [comment]
もう自分の手を離れたようなものなので0.9.1のように普通にバージョンアップしていけばいいのではないかと思います。
（dの字は自分の名前のプレフィックスなので…。）

あと、ソフトウエア上のバージョン表記を変更するのにversion.batを更新する必要があったかと思います。
それ以外で残ってるのは完成版をビルドしてversion.hが出来たらコミットしてタグを切るぐらいです。

バージョンアップで必要だった作業は多分それぐらいだったと思います。
現状お任せしている状態ですが、よろしくお願いします。

**Comment by southly** [comment]
では次バージョンは 0.9.1 にしましょう。
version.bat と version.h もそれにあわせて更新しておきます。

**Comment by southly** [comment]
Wiki/マニュアルを更新

**Comment by southly** [comment]
特に問題がなければ b1898f6f8b5ae68f660f0fbf5925a5d7f1acfa69 でリリースします。

**Comment by southly** [comment]
ad75fcb3b7c3ce03a9fabb42a817ba13ea302eb8 に タグ `0.9.1` を打ちました。
[ckw-mod/ckw-mod.github.com](https://github.com/ckw-mod/ckw-mod.github.com) の方に ckw-mod-0.9.1.zip を push しておきました。

**Comment by southly** [comment]
http://ckw-mod.github.com/ から ckw-mod-0.9.1.zip をダウンロードできるようにしました。

sf.jp の方は参加申請を送ったものの回答がないため保留中です。
@deflis さんの手の空いているときにでも push して置いてください。

`0.9.1` はクローズしておきます。
