### ISSUE TITLE
GCC でビルドできない

### ISSUE THREAD

**Issue by wantora** [ckw-mod/ckw-mod#14]
(#13 を  issue として再登録させていただきました。)

下記の問題があり GCC 4 でビルド出来ません。
1. makefile-gcc が GCC 4 に対応していない
2. `PRTL_USER_PROCESS_PARAMETERS` と `STARTF_TITLEISLINKNAME` の定義が足らない
3. [Visual C++ の _s 付き関数](http://msdn.microsoft.com/ja-jp/library/8ef0s5kh.aspx) が GCC に存在しない

参考として以前修正したものをおいておきます。 wantora/ckw-mod@7d9d9da9cbb0c8a9513e8bf1cea78b7dd310d46e

**Comment by southly** [comment]
個人的に作るときは C++ の仕様にない _s 付き関数は使わないのですが、
C11 に含まれたみたいですし、そのうち gcc でも使えるようになると期待して
お茶を濁す方向で対応しようかなと思います。

southly/ckw-mod@0fb4ad7465d9db0ee47bd02cce447ca63d8523e4 (gcc 4.6.2)
- _s 付き関数は `compat.h` で何とかする
- `ddk/ntapi.h` は `winternl.h` と似たようなところで include
- wWinMain は引数を利用していないので WinMain にする
- makefile-gcc は変数名とか個人的な好みで変えてしまいました

**Comment by southly** [comment]
警告に対する対処やセキュリティの向上はこの先対応していくということで。

**Comment by wantora** [comment]
おお、ありがとうございます。一応こちらでも GCC 4.6.2 (mingw32) でビルドができることを確認しました。

一つ気になるのですが、GCC で `STARTF_TITLEISLINKNAME` の部分を無視していいのでしょうか？ GCC でビルドした時だけ問題が発生するのはまずい気がします。 (Windows 7 x64 は持っていないので確認できないのですが…)

**Comment by southly** [comment]
私の環境は Win7 64bit なのですが問題ありませんでした。
64bit アプリとしてビルドしたときに問題だったのかなと思っていたのですが。

**Comment by wantora** [comment]
なるほど。

でも、x64対応の [MinGW-w64](http://mingw-w64.sourceforge.net/) もあるので一応対応しておいたほうがいいと思うのですが、どうでしょうか。(まあ、MinGW-w64 はサポートしない、というのもアリですが)

**Comment by southly** [comment]
MinGW-w64 のバイナリを [TDM-GCC](http://tdm-gcc.tdragon.net/) からダウンロードして対応しておきました。

<del>southly/ckw-mod@8b1858fd71e094bbae160521f620c74cc87fdaf2</del>

southly/ckw-mod@0709e1eaef0fab3b5e6d674ec346803c4211f424
- `ddk/ntapi.h` がないので include しない
- `winternl.h` はあるけれど定義が異なるので使わない
- リソースのコンパイルで `syntax error` になったので <del>`windows.h`</del>`winresrc.h` を include

`STARTF_TITLEISLINKNAME` の部分はあってもなくても変わらないようでしたので消すのはやめにしました。

**Comment by wantora** [comment]
素晴らしいです。

**Comment by southly** [comment]
一応 MinGW-w64 でもビルドできるようにしましたが、サポートするとは言い難いです。
おまけ的な位置づけだと思ってください。

**Comment by southly** [comment]
修正をマージしておきました。

**Comment by wantora** [comment]
マージありがとうございます。
