### ISSUE TITLE
ckw.cfgの「Ckw*chdir:」で存在しないディレクトリを指定すると無言で即終了してしまう

### ISSUE THREAD

**Issue by hymkor** [ckw-mod/ckw-mod#19]
ckw.cfgの「Ckw*chdir:」で存在しないディレクトリを指定すると即終了するようです。エラーメッセージの類も出ないため、ckw.cfg の記述ミスと分かりづらいです。

だいぶと前にソースを拝見した時、Ckw*chdir で取得したディレクトリ名について特にチェックもなく、そのまま CreateProcess に投げ、そのままプロセスを起動できずにエラー終了していたように見えました。

もし、そのままであるようでしたら、起動前に自前で chdir するか、ディレクトリの存在チェックをする処理を入れていただければと存じます。

以上、よろしくお願いいたします。

**Comment by southly** [comment]
無言で終了してしまうのを次回のリリースにまわしてしまうのもどうかと思いましたので、
最低限の対処をしておきました。 #20
どうあるべきかはもうちょっと考えてみます。

**Comment by hymkor** [comment]
バージョン ad75fcb3b7c3ce03a9fabb42a817ba13ea302eb の時点で
- 正しいディレクトリを指定すると、そこへちゃんと chdir している
- 誤ったディレクトリを指定すると、現在のカレントディレクトリのまま起動はする

ことを確認いたしました。ご対応誠にありがとうございました。
